AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 40

Metrics/ParameterLists:
  Max: 10
